/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package companystockexchange.Layer;

import companystockexchange.Controller.MainController;
import companystockexchange.Helper.Helper;
import companystockexchange.Model.MainModel;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Wibby Chandra
 */
public class Admin extends javax.swing.JFrame {
    MainModel model = new MainModel();
    MainController controller = new MainController();
    
    Helper helper = new Helper();
    String product_id;
    ResultSet rs;

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        getAllData();
        clear();
    }
    public void getAllData(){
        this.rs = controller.getShareHolders();
        loadtable(this.rs);
    }
    
    public void loadtable(ResultSet rs){
        tb_list.setModel(DbUtils.resultSetToTableModel(rs));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_namaadmin = new javax.swing.JTextField();
        tf_perlembaradmin = new javax.swing.JTextField();
        tf_persenadmin = new javax.swing.JTextField();
        tf_hargajualadmin = new javax.swing.JTextField();
        dp_tanggaladmin = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_list = new javax.swing.JTable();
        btn_updatedata = new javax.swing.JButton();
        btn_tambahdata = new javax.swing.JButton();
        btn_mengahpusdata = new javax.swing.JButton();
        tf_cari = new javax.swing.JTextField();
        btn_cariid = new javax.swing.JButton();
        btn_carinama = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Shareholder's Name");

        jLabel3.setText("Date Noted");

        jLabel4.setText("Shareholding per Sheet");

        jLabel7.setText("Shareholding Percentage in %");

        jLabel5.setText("Shares Selling Price");

        tf_namaadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_namaadminActionPerformed(evt);
            }
        });

        tb_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_list);

        btn_updatedata.setText("Update Data");
        btn_updatedata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatedataActionPerformed(evt);
            }
        });

        btn_tambahdata.setText("Insert Data");
        btn_tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahdataActionPerformed(evt);
            }
        });

        btn_mengahpusdata.setText("Delete Data");
        btn_mengahpusdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mengahpusdataActionPerformed(evt);
            }
        });

        btn_cariid.setText("Search by ID");
        btn_cariid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariidActionPerformed(evt);
            }
        });

        btn_carinama.setText("Search by Name");
        btn_carinama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carinamaActionPerformed(evt);
            }
        });

        jLabel6.setText("Search");

        btn_logout.setText("Log Out");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_namaadmin)
                            .addComponent(dp_tanggaladmin, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(tf_perlembaradmin)
                            .addComponent(tf_persenadmin)
                            .addComponent(tf_hargajualadmin)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_tambahdata)
                        .addGap(61, 61, 61)
                        .addComponent(btn_updatedata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(btn_mengahpusdata)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(15, 15, 15)
                        .addComponent(tf_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cariid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_carinama)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_logout)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_logout)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_namaadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dp_tanggaladmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_perlembaradmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_persenadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_hargajualadmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambahdata)
                    .addComponent(btn_mengahpusdata)
                    .addComponent(btn_updatedata)
                    .addComponent(jLabel6)
                    .addComponent(tf_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cariid)
                    .addComponent(btn_carinama))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_namaadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_namaadminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_namaadminActionPerformed

    private void btn_tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahdataActionPerformed
        // TODO add your handling code here:
        try{
            String name = tf_namaadmin.getText();
            Date date = dp_tanggaladmin.getDate();
            String sheet = tf_perlembaradmin.getText();
            String percent = tf_persenadmin.getText();
            String price = tf_hargajualadmin.getText();
            
            model.setName(name);
            model.setTanggal(date);
            model.setLembar(sheet);
            model.setPersen(percent);
            model.setHarga(price);
            
            Boolean result = controller.create(model);
            if(result){
                JOptionPane.showMessageDialog(null, "Successfully Inserting Data");
            }
            else{
                JOptionPane.showMessageDialog(null, "Unsuccessfully Inserting Data");
            }
            clear();
            getAllData();
        }
        catch (Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_tambahdataActionPerformed

    private void btn_mengahpusdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mengahpusdataActionPerformed
        // TODO add your handling code here:
        try{
            Boolean result = controller.delete(product_id);
            
            if(result){
                JOptionPane.showMessageDialog(null, "Successfully Deleting Data");
            }
            else{
                JOptionPane.showMessageDialog(null, "Unsuccessfully Deleting Data");
            }
            clear();
            getAllData();
        }
        catch(Exception ex){
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_mengahpusdataActionPerformed

    private void btn_carinamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carinamaActionPerformed
        // TODO add your handling code here:
        search("name", tf_cari.getText());
    }//GEN-LAST:event_btn_carinamaActionPerformed

    private void btn_updatedataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatedataActionPerformed
        // TODO add your handling code here:
        try{
            String name = tf_namaadmin.getText();
            Date date = dp_tanggaladmin.getDate();
            String sheet = tf_perlembaradmin.getText();
            String percent = tf_persenadmin.getText();
            String price = tf_hargajualadmin.getText();
            
            model.setName(name);
            model.setTanggal(date);
            model.setLembar(sheet);
            model.setPersen(percent);
            model.setHarga(price);
            
            Boolean result = controller.update(product_id, model);
            if(result){
                JOptionPane.showMessageDialog(null, "Berhasil Mengubah Data");
            }
            else{
                JOptionPane.showMessageDialog(null, "Gagal Mengubah Data");
            }
            clear();
            getAllData();
        }
        catch(Exception ex){
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btn_updatedataActionPerformed

    private void tb_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_listMouseClicked
        // TODO add your handling code here:
        try{
            String id = helper.getValueRows(tb_list, 0);
            String name = helper.getValueRows(tb_list, 1);
            String date = helper.getValueRows(tb_list, 2);
            String sheet = helper.getValueRows(tb_list, 3);
            String percent = helper.getValueRows(tb_list, 4);
            String price = helper.getValueRows(tb_list, 5);
            
            btn_updatedata.setEnabled(true);
            btn_mengahpusdata.setEnabled(true);
            
            this.product_id = id;
            tf_namaadmin.setText(name);
            tf_perlembaradmin.setText(sheet);
            dp_tanggaladmin.setDate(new Date(helper.parseStringToDatepickerFormat(date)));
            tf_persenadmin.setText(percent);
            tf_hargajualadmin.setText(price);
        }
        catch (Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tb_listMouseClicked

    private void btn_cariidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariidActionPerformed
        // TODO add your handling code here:
        search("id", tf_cari.getText());
    }//GEN-LAST:event_btn_cariidActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    public void search(String type, String query){
        try{
            if(query.isEmpty()){
                this.rs = controller.getShareHolders();
            }
            else if(type.equals("id") && !query.isEmpty()){
                this.rs = controller.showById(query);
            }
            else if(type.equals("name") && !query.isEmpty()){
                this.rs = controller.showByName(query);
            }
            
            loadtable(this.rs);
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    public void clear(){
        tf_namaadmin.setText("");
        dp_tanggaladmin.setDate(null);
        tf_perlembaradmin.setText("");
        tf_persenadmin.setText("");
        tf_hargajualadmin.setText("");
        
        btn_updatedata.setEnabled(false);
        btn_mengahpusdata.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cariid;
    private javax.swing.JButton btn_carinama;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_mengahpusdata;
    private javax.swing.JButton btn_tambahdata;
    private javax.swing.JButton btn_updatedata;
    private org.jdesktop.swingx.JXDatePicker dp_tanggaladmin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_list;
    private javax.swing.JTextField tf_cari;
    private javax.swing.JTextField tf_hargajualadmin;
    private javax.swing.JTextField tf_namaadmin;
    private javax.swing.JTextField tf_perlembaradmin;
    private javax.swing.JTextField tf_persenadmin;
    // End of variables declaration//GEN-END:variables
}
