/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package companystockexchange.Layer;
import javax.swing.JOptionPane;
/**
 *
 * @author Abner
 */
public class BuyShare extends javax.swing.JFrame {

    /**
     * Creates new form BuyShares
     */
    public BuyShare() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tf_Percent = new javax.swing.JTextField();
        tf_sheet = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_set = new javax.swing.JButton();
        btn_buy = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_total = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Back To Profile Menu");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 170, 23);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 776, 576);

        tf_Percent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_PercentActionPerformed(evt);
            }
        });
        getContentPane().add(tf_Percent);
        tf_Percent.setBounds(210, 70, 170, 20);
        getContentPane().add(tf_sheet);
        tf_sheet.setBounds(210, 100, 170, 20);

        jLabel3.setText("Share Price Per Sheet");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 104, 160, 20);

        jLabel4.setText("How Much You Wanna Buy");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 134, 160, 20);

        jLabel5.setText("Total Price");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 220, 170, 14);

        btn_set.setText("Set");
        btn_set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setActionPerformed(evt);
            }
        });
        getContentPane().add(btn_set);
        btn_set.setBounds(260, 160, 49, 23);

        btn_buy.setText("Buy");
        btn_buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buyActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buy);
        btn_buy.setBounds(210, 340, 51, 23);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(210, 130, 170, 20);

        jLabel2.setText("Share Price Per Percent");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 74, 160, 20);

        ta_total.setColumns(20);
        ta_total.setRows(5);
        jScrollPane1.setViewportView(ta_total);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 220, 270, 110);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 390, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Profile profile = new Profile();
        profile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_PercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_PercentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_PercentActionPerformed

    private void btn_setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setActionPerformed
        // TODO add your handling code here:
        ta_total.setText(jSpinner1.getValue().toString());
    }//GEN-LAST:event_btn_setActionPerformed

    private void btn_buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buyActionPerformed
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Are You Sure Want To "
                + "Buy?","Buy Share",JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.YES_OPTION)
            JOptionPane.showMessageDialog(null, "Transaction Complete!");
        else 
            JOptionPane.showMessageDialog(this, "Transaction Canceled!");
        
    }//GEN-LAST:event_btn_buyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyShare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buy;
    private javax.swing.JButton btn_set;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea ta_total;
    private javax.swing.JTextField tf_Percent;
    private javax.swing.JTextField tf_sheet;
    // End of variables declaration//GEN-END:variables
}
