/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package companystockexchange.Layer;
import javax.swing.JOptionPane;
/**
 *
 * @author Abner
 */
public class SellShare extends javax.swing.JFrame {

    /**
     * Creates new form SellShare
     */
    public SellShare() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tf_usershare = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_totalprice = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btn_set = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        tf_sellpercent = new javax.swing.JTextField();
        tf_sellprice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btn_sell = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel6.setText("Your Share");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 40, 140, 14);
        jPanel1.add(tf_usershare);
        tf_usershare.setBounds(170, 40, 200, 20);

        ta_totalprice.setColumns(20);
        ta_totalprice.setRows(5);
        jScrollPane1.setViewportView(ta_totalprice);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(170, 220, 210, 110);

        jLabel5.setText("Total Price :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 220, 140, 14);

        btn_set.setText("Set");
        btn_set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setActionPerformed(evt);
            }
        });
        jPanel1.add(btn_set);
        btn_set.setBounds(230, 160, 60, 23);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        jSpinner1.setToolTipText("");
        jPanel1.add(jSpinner1);
        jSpinner1.setBounds(170, 130, 200, 20);

        jLabel4.setText("How Much You Wanna Sell");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 130, 150, 20);

        tf_sellpercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_sellpercentActionPerformed(evt);
            }
        });
        jPanel1.add(tf_sellpercent);
        tf_sellpercent.setBounds(170, 100, 200, 20);

        tf_sellprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_sellpriceActionPerformed(evt);
            }
        });
        jPanel1.add(tf_sellprice);
        tf_sellprice.setBounds(170, 70, 200, 20);

        jLabel3.setText("Shareholding Percentage in %");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 100, 150, 14);

        jLabel2.setText("Selling Share Price Per Sheet");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 70, 150, 14);

        jButton1.setText("Back To Profile Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 0, 160, 23);

        btn_sell.setText("Sell");
        btn_sell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sellActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sell);
        btn_sell.setBounds(230, 340, 73, 23);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Profile profile = new Profile();
        profile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_sellpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_sellpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_sellpriceActionPerformed

    private void tf_sellpercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_sellpercentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_sellpercentActionPerformed

    private void btn_setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setActionPerformed
        // TODO add your handling code here:
        ta_totalprice.setText(jSpinner1.getValue().toString());
    }//GEN-LAST:event_btn_setActionPerformed

    private void btn_sellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sellActionPerformed
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Sure Want To "
                + "Sell?","Sell",JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.YES_OPTION)
            JOptionPane.showMessageDialog(null, "Sell Complete!");
        else
            JOptionPane.showMessageDialog(null, "Sell Is Canceled!");
    }//GEN-LAST:event_btn_sellActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellShare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellShare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sell;
    private javax.swing.JButton btn_set;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTree jTree1;
    private javax.swing.JTextArea ta_totalprice;
    private javax.swing.JTextField tf_sellpercent;
    private javax.swing.JTextField tf_sellprice;
    private javax.swing.JTextField tf_usershare;
    // End of variables declaration//GEN-END:variables
}
